/* GENERATED by tools/gen_world.py - do not edit by hand. */
#ifndef LIL_GEN_H
#define LIL_GEN_H

#include "global.h"

extern u64 gLilTex_grass[128];
extern u64 gLilTex_flag[128];
extern u64 gLilTex_marble[128];
extern u64 gLilTex_water[128];
extern u64 gLilTex_hedge[128];
extern u64 gLilTex_cobble[128];
extern u64 gLilTex_brick[128];
extern u64 gLilTex_plain[128];
extern u64 gLilTex_rune[128];

extern Gfx gLilRoseKnight_BodyDL[];
extern Gfx gLilRoseKnight_HeadDL[];
extern Gfx gLilRoseKnight_PlumeDL[];
extern Gfx gLilRoseKnight_ShieldDL[];
extern Gfx gLilRoseKnight_SwordDL[];
extern Gfx gLilThornling_BodyDL[];
extern Gfx gLilThornling_ThornsDL[];
extern Gfx gLilThornling_EyesDL[];
extern Gfx gLilPetalWisp_CoreDL[];
extern Gfx gLilPetalWisp_PetalsDL[];
extern Gfx gLilPetalShot_PetalDL[];
extern Gfx gLilThornSpike_SpikeDL[];
extern Gfx gLilPlate_BaseDL[];
extern Gfx gLilPlate_TopDL[];
extern Gfx gLilPathPad_PadDL[];
extern Gfx gLilPortal_RingDL[];
extern Gfx gLilPortal_GlowDL[];
extern Gfx gLilLilithStatue_RobeDL[];
extern Gfx gLilLilithStatue_HeadDL[];
extern Gfx gLilLilithStatue_ArmsDL[];
extern Gfx gLilLilithStatue_RoseDL[];
extern Gfx gLilLilithStatue_LeafDL[];
extern Gfx gLilLilithStatue_HaloDL[];
extern Gfx gLilBramble_VinesDL[];
extern Gfx gLilBramble_ThornsDL[];
extern Gfx gLilBarrier0_PostsDL[];
extern Gfx gLilBarrier0_ThornsDL[];
extern Gfx gLilBarrier0_BarsDL[];
extern Gfx gLilBarrier1_PostsDL[];
extern Gfx gLilBarrier1_RosesDL[];
extern Gfx gLilBarrier1_BudsDL[];
extern Gfx gLilBarrier1_ArchDL[];
extern Gfx gLilPetalRing_RingDL[];
extern Gfx gLilWarden_BodyDL[];
extern Gfx gLilWarden_HeadDL[];
extern Gfx gLilWarden_CrownDL[];
extern Gfx gLilWarden_ArmsDL[];
extern Gfx gLilWarden_MaceDL[];
extern Gfx gLilWarden_RootsDL[];
extern Gfx gLilQueen_GownDL[];
extern Gfx gLilQueen_BustDL[];
extern Gfx gLilQueen_HeadDL[];
extern Gfx gLilQueen_CrownDL[];
extern Gfx gLilQueen_ArmsDL[];
extern Gfx gLilQueen_PetalsDL[];
extern CollisionHeader gLilBarrierCol;
extern CollisionHeader gLilBrambleCol;
extern CollisionHeader gLilPlateCol;

// Switch flags used by the placed actors (see tools/gen_world.py)
#define LIL_FLAG_SANCTUARY_GATE 0x01
#define LIL_FLAG_ENTRY_PLATE 0x02
#define LIL_FLAG_GALLERY_CLEAR 0x03
#define LIL_FLAG_PATH_SOLVED 0x04
#define LIL_FLAG_KNIGHTS_CLEAR 0x05
#define LIL_FLAG_WARDEN_DEAD 0x06
#define LIL_FLAG_QUEEN_DEAD 0x07

#define LIL_PORTAL_TO_CRYPT 0
#define LIL_PORTAL_TO_SANCTUARY 1
#define LIL_PORTAL_HOME 2
#define LIL_BARRIER_CRYPT 0
#define LIL_BARRIER_SANCTUARY 1

#endif
