#ifndef LILITH_H
#define LILITH_H

/**
 * Lilith's Lullaby: White Rose Sanctuary
 *
 * Shared declarations for the whole mod. Everything in this mod is self contained: there are no dependencies on other
 * mods. All global symbols exported from this mod use the `Lil`/`gLil`/`sLil` prefixes to avoid clashing with the game.
 */

#include "modding.h"
#include "global.h"
#include "recomputils.h"

/* ------------------------------------------------------------------------------------------------------------------
 * Custom scene slots.
 *
 * The vanilla game has a number of empty (unused) entries in its scene table and its entrance table. Each of our
 * scenes permanently owns one scene slot and one entrance slot. Nothing is shared or multiplexed, which means the game
 * can always tell which scene it is loading from the scene id alone (for example after dying and continuing).
 * The Scene API mod uses SCENE_UNSET_01 and ENTR_SCENE_UNSET_08, so we deliberately use different slots.
 * ---------------------------------------------------------------------------------------------------------------- */
#define LIL_SCENE_SANCTUARY SCENE_UNSET_3A
#define LIL_SCENE_CRYPT SCENE_UNSET_31

#define LIL_ENTR_SCENE_SANCTUARY ENTR_SCENE_UNSET_37
#define LIL_ENTR_SCENE_CRYPT ENTR_SCENE_UNSET_2E

// ENTRANCE(scene, spawn) token pastes ENTR_SCENE_##scene
#define LIL_ENTRANCE_SANCTUARY(spawn) ENTRANCE(UNSET_37, spawn)
#define LIL_ENTRANCE_CRYPT(spawn) ENTRANCE(UNSET_2E, spawn)

// Sanctuary spawns
#define LIL_SPAWN_SANCTUARY_WARP 0  // arriving by Lilith's Lullaby (Soaring style arrival)
#define LIL_SPAWN_SANCTUARY_CRYPT 1 // coming back out of the Crypt
#define LIL_SPAWN_SANCTUARY_COUNT 2
// Crypt spawns
#define LIL_SPAWN_CRYPT_ENTRY 0
#define LIL_SPAWN_CRYPT_COUNT 1

#define LIL_IS_CUSTOM_SCENE(sceneId) (((sceneId) == LIL_SCENE_SANCTUARY) || ((sceneId) == LIL_SCENE_CRYPT))

// EntranceTableEntry.flags: bits 0-6 are the transition type used when leaving through this entrance,
// bits 7-13 are the transition type used when arriving.
#define LIL_ENTRANCE_FLAGS(arriveTrans, leaveTrans) ((((arriveTrans) & 0x7F) << 7) | ((leaveTrans) & 0x7F))

/* ------------------------------------------------------------------------------------------------------------------
 * The song.
 * ---------------------------------------------------------------------------------------------------------------- */
#define LIL_LULLABY_LENGTH 7

// Called when Lilith's Lullaby is played while the actor that registered the handler is alive. Handlers must check
// their own range. Return true to consume the song (which stops it from warping the player).
typedef s32 (*LilLullabyHandler)(Actor* actor, PlayState* play);

void Lil_RegisterLullabyListener(Actor* actor, LilLullabyHandler handler);
void Lil_UnregisterLullabyListener(Actor* actor);

// Game frame (play->gameplayFrames) on which the song was last played, or 0 if it never was in this play session.
extern u32 gLilLullabyFrame;
// Returns true if the song was played at most `frames` frames ago.
s32 Lil_LullabyPlayedRecently(PlayState* play, u32 frames);

// While non-zero the song cannot warp the player (used during boss fights and set pieces).
extern u8 gLilWarpBlocked;

// Warp the player out of the custom scenes back to where they were (or to Clock Town if that's unknown).
void Lil_RequestWarpHome(PlayState* play);

/* ------------------------------------------------------------------------------------------------------------------
 * Scene registration (scene_loader.c). The scene data itself is generated by tools/gen_world.py.
 * ---------------------------------------------------------------------------------------------------------------- */
typedef struct LilSceneDef {
    /* 0x00 */ SceneCmd* header;
    /* 0x04 */ SceneCmd** rooms;
    /* 0x08 */ s32 numRooms;
    /* 0x0C */ s32 sceneId;
    /* 0x10 */ s32 entranceSceneId;
    /* 0x14 */ s32 numSpawns;
    /* 0x18 */ const char* name;
} LilSceneDef;

extern LilSceneDef gLilSceneDefs[];
extern const s32 gLilNumSceneDefs;

const LilSceneDef* Lil_FindSceneDef(s32 sceneId);
void Lil_RegisterTables(void);

/* ------------------------------------------------------------------------------------------------------------------
 * Custom actors.
 *
 * Actors are registered into unused entries of gActorOverlayTable at runtime (no patching, so no conflicts with other
 * mods). The generated scene data refers to actors through placeholder ids, LIL_ACTOR_ID(slot), which are swapped for
 * the real ids once the actors are registered.
 * ---------------------------------------------------------------------------------------------------------------- */
typedef enum LilActorSlot {
    LIL_ACT_LILITH_STATUE, // Sanctuary: hears the song and unseals the crypt gate
    LIL_ACT_RETURN_PORTAL, // glowing rose circle: crypt entrance / exit, or "go home"
    LIL_ACT_BARRIER,       // thorn wall / white rose gate (dynamic collision), opens on a switch flag
    LIL_ACT_PLATE,         // pressure plate puzzle piece
    LIL_ACT_PATH_PUZZLE,   // "Petal Path": repeat the pattern of glowing pads
    LIL_ACT_BRAMBLE,       // brambles that burn or blast away
    LIL_ACT_ARENA,         // wave arena controller
    LIL_ACT_THORNLING,     // enemy
    LIL_ACT_PETAL_WISP,    // enemy
    LIL_ACT_ROSE_KNIGHT,   // enemy
    LIL_ACT_HAZARD,        // petal shots, thorn spikes, shockwaves
    LIL_ACT_BOSS_WARDEN,   // boss: Thorn Warden
    LIL_ACT_BOSS_QUEEN,    // boss: the Queen of Thorns
    LIL_ACT_COUNT
} LilActorSlot;

#define LIL_ACTOR_PLACEHOLDER_BASE 0x0700
#define LIL_ACTOR_ID(slot) (LIL_ACTOR_PLACEHOLDER_BASE + (slot))

extern s16 gLilActorIds[LIL_ACT_COUNT];

typedef struct LilActorDef {
    ActorProfile* profile;
    const char* name;
} LilActorDef;

// Implemented in actors/actor_registry.c
extern LilActorDef gLilActorDefs[LIL_ACT_COUNT];
void Lil_RegisterActors(void);

// A list of actor spawn entries that uses placeholder ids (generated).
typedef struct LilActorList {
    ActorEntry* entries;
    s32 count;
} LilActorList;

extern LilActorList gLilActorLists[];
extern const s32 gLilNumActorLists;

#endif /* LILITH_H */
